### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by AkiSchmatzler** [rschlaikjer/erlang-atrace-flamegraphs#8]
I've been trying to run this project inside my WSL. When compiling, I get the following mistake : 
![image](https://user-images.githubusercontent.com/65312113/225650777-cdc1c81f-3a49-4171-875b-10c8f2dc6283.png)

As I am not familiar with Erlang, I was wondering if you could help me figure this out.

**Comment by rschlaikjer** [comment]
Looks like that version of lager wasn't compatible with Erlang 25. I've updated the dependency, so you should be able to pull and run `rebar3 upgrade --all` to fix it.
